name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build example
        run: nix -L build .#example
