name: Pages

on:
  workflow_call:
    inputs:
      output_name:
        type: string
        required: true
        description: |
          Flake output to deploy to Pages. This is the string you passed as
          `outputName` when calling `coricamu.lib.generateFlakeOutputs`.

      directory:
        type: string
        default: '.'
        required: false
        description: |
          This can be used to specify a subdirectory if your flake is not at
          the repository root.

jobs:
  build:
    name: Build

    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ${{inputs.output_name}}
        run: nix -L build ${{inputs.directory}}#${{inputs.output_name}}

      - name: Prepare ${{inputs.output_name}} for upload
        run: cp -r --dereference --no-preserve=mode,ownership result/ public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    name: Deploy

    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/${{ github.event.repository.default_branch }}'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    concurrency:
      group: github-pages
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Deploy ${{inputs.output_name}} to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
